name: ascii_art_app
description: A new Flutter project to convert photos to ASCII art.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0" # Ensure this matches your Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5 # Use the latest version compatible with your Flutter SDK
  path_provider: ^2.0.9 # Use the latest version compatible with your Flutter SDK

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
